{{- if eq .Values.n8n.deploymentMode "scale" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webhook
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: webhook
    spec:
      restartPolicy: Always
      containers:
        - name: webhook
          image: n8nio/n8n:{{ .Values.n8n.imageTag }}
          args: ["webhook"]
          envFrom:
          - configMapRef:
              name: n8n-configmap-env
          resources:
            limits:
              memory: {{ .Values.resources.memoryLimit }}

---
apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  type: ClusterIP
  selector:
    service: webhook
  ports:
    - port: 5678
{{- end }}
